exclude: '^docs/|/migrations/'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  # djhtml runs on anything inside a templates dir which could contain Django Template Language
  # this includes dynamically created js and css files.
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        files: '/templates/.+\.html$'
        entry: djhtml --tabwidth 2
      - id: djcss
        files: '/templates/.+\.css$'
        entry: djcss --tabwidth 2
      - id: djjs
        files: '/templates/.+\.js$'
        entry: djjs --tabwidth 2

  # prettier runs on all css and js that is in a /static/css|js/ dir or app_name/static/app_name/css|js/.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        args: ['--tab-width', '2', '--single-quote', '--print-width', '120']
        files: >
          (?x)^(
            /static/(css|js)/.+\.(css|js)$|
            (?P<a>[^/]*)/static/(?P=a)/(css|js)/.+\.(css|js)$|
            .html$
          )
        exclude: '/templates/'

  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.13.0'
    hooks:
      - id: django-upgrade
        args: ['--target-version', '4.1']

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
