# Generated by Django 4.1.7 on 2023-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_blocks', models.ManyToManyField(to='content_blocks.contentblock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
