# Generated by Django 4.2.1 on 2023-05-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_blocks', '0003_alter_contentblocktemplatefield_unique_together_and_more'),
        ('sites', '0002_alter_domain_unique'),
        ('pages', '0002_page_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sites',
        ),
        migrations.CreateModel(
            name='PageSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_blocks', models.ManyToManyField(to='content_blocks.contentblock')),
                ('sites', models.ManyToManyField(blank=True, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_blocks', models.ManyToManyField(to='content_blocks.contentblock')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
