# Generated by Django 4.2.6 on 2023-10-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("content_blocks", "0006_iframefield_contentblockfield_iframe"),
        ("content_blocks", "0007_contentblock_name_and_more"),
        ("content_blocks", "0008_auto_20231019_1729"),
        ("content_blocks", "0009_alter_contentblock_name"),
    ]

    dependencies = [
        ("content_blocks", "0005_alter_contentblockcollection_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="IframeField",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content_blocks.contentblockfield",),
        ),
        migrations.AddField(
            model_name="contentblockfield",
            name="iframe",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Used to identify content blocks in the content block editor. Defaults to <content_block_template_name> #<content_block_id>",
                max_length=320,
            ),
        ),
        migrations.AlterField(
            model_name="contentblocktemplatefield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("TextField", "Text Field"),
                    ("ContentField", "Content Field"),
                    ("ImageField", "Image Field"),
                    ("NestedField", "Nested Field"),
                    ("CheckboxField", "Checkbox Field"),
                    ("ChoiceField", "Choice Field"),
                    ("ModelChoiceField", "Model Choice Field"),
                    ("FileField", "File Field"),
                    ("VideoField", "Video Field"),
                    ("EmbeddedVideoField", "Embedded Video Field"),
                    ("IframeField", "Iframe Field"),
                ],
                max_length=32,
            ),
        ),
    ]
